name: Flask CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:


      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: make venv
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      
      - name: run flask
        run: |
          . venv/bin/activate
          export FLASK_APP=app.py
      
      - name: Build & Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kids-in-seoul-flask .
          docker push ${{ secrets.DOCKER_USERNAME }}/kids-in-seoul-flask:latest

      - name: SSH into development server and deploy
        uses: appleboy/ssh-action@master
        if : contains(github.ref,'main')
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script : |
            docker rm -f $(docker ps -qa)
            docker pull ${{ secrets.DOCKER_USERNAME }}/kids-in-seoul-flask
            docker-compose up -d
            docker image prune -f


## time
  current-time:
    needs: CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00"
      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}"
        shell: bash
